@startuml

:Fruitore: as Admin
(Accesso fruitore) as (UseF1)
(Creazione fruitore) as (UseF2)
(Visualizzazione informazioni app) as (UseF3)
(Visualizzazione offerte categoria) as (UseF5)
(Visualizzazione offerte personali) as (UseF6)
(Offerta di baratto) as (UseF7)
(Modifica stato offerta) as (UseF8)

Admin -left-> (UseF3)
Admin -up-> (UseF1)
Admin -up-> (UseF2)
Admin -right-> (UseF6)
Admin --> (UseF5)
Admin --> (UseF7)
Admin --> (UseF8)

(UseF1) .right.> (UseF2): <<include>>

(Accesso configuratore) as (Use1)
(Creazione configuratore) as (Use2)
(Salvataggio dati) as (Use3)
(Visualizzazione gerarchie) as (Use4)
(Creazione gerarchia) as (Use5)
(Aggiunta categoria) as (Use6)
(Configurazione parametri) as (Use7)

:Configuratore: as Admin2
Admin2 -left-> (Use4)
Admin2 --> (Use5)
Admin2 --> (Use3)
Admin2 -right-> (Use2)
Admin2 -up-> (Use1)
Admin2 -up-> (Use7)
Admin2 --> (UseF5)


(Use1) ..> (Use2): <<include>>
(Use5) ..> (Use6): <<include>>
(Use5) ..> (Use3): <<include>>


@enduml