@startuml

:Fruitore: as Admin
(Accesso fruitore) as (UseF1)
(Creazione fruitore) as (UseF2)
(Visualizzazione informazioni app) as (UseF3)

Admin --> (UseF3)
Admin --> (UseF1)
Admin --> (UseF2)
(UseF1) .right.> (UseF2): <<include>>


(Accesso configuratore) as (Use1)
(Creazione configuratore) as (Use2)
(Salvataggio dati) as (Use3)
(Visualizzazione gerarchie) as (Use4)
(Creazione gerarchia) as (Use5)
(Aggiunta categoria) as (Use6)
(Configurazione parametri) as (Use7)

:Configuratore: as Admin2
Admin2 --> (Use4)
Admin2 --> (Use5)
Admin2 --> (Use3)
Admin2 -right-> (Use2)
Admin2 --> (Use1)
Admin2 --> (Use7)

(Use1) ..> (Use2): <<include>>
(Use5) ..> (Use6): <<include>>
(Use5) ..> (Use3): <<include>>


@enduml