@startuml

autonumber
title Accesso Configuratore

actor Configuratore
participant View
participant Controller
Configuratore -> View: Richiesta accesso al profilo
View -> Configuratore: Richiesta username
Configuratore -> View: Inserimento username
View -> Controller: Invio username
Controller ->Controller: Controllo esistenza \nusername

alt Username esistente
    Controller --> View: Username esistente
    View -> Configuratore: Richiesta password
    Configuratore -> View: Inserimento password
    View -> Controller: Invio password
    Controller -> Controller: Autenticazione\npassword

    alt Password corretta
        Controller --> View: Password corretta
        View --> Configuratore: Login effettuato

    else Password errata
        Controller --> View: Password errata
        View --> Configuratore: Login fallito
    end

else Username inesistente
    Controller --> View: Username inesistente
    View --> Configuratore: Autenticazione fallita


end

@enduml