@startuml

autonumber
title Accesso Configuratore

actor Configuratore
participant View
participant UserDataStore
Configuratore -> View: Richiesta accesso al profilo
View -> Configuratore: Richiesta username
Configuratore -> View: Inserimento username
View -> UserDataStore: Invio username
UserDataStore ->UserDataStore: Controllo esistenza \nusername

alt Username esistente
    UserDataStore --> View: Username esistente
    View -> Configuratore: Richiesta password
    Configuratore -> View: Inserimento password
    View -> UserDataStore: Invio password
    UserDataStore -> UserDataStore: Autenticazione\npassword

    alt Password corretta
        UserDataStore --> View: Password corretta
        View --> Configuratore: Login effettuato

    else Password errata
        UserDataStore --> View: Password errata
        View --> Configuratore: Login fallito
    end

else Username inesistente
    UserDataStore --> View: Username inesistente
    View --> Configuratore: Autenticazione fallita


end

@enduml