@startuml

(Accesso configuratore) as (Use1)
(Creazione configuratore) as (Use2)
(Salvataggio dati) as (Use3)
(Visualizzazione gerarchie) as (Use4)
(Creazione gerarchia) as (Use5)
(Aggiunta categoria) as (Use6)



:Configuratore: as Admin
Admin --> (Use4)
Admin --> (Use5)
Admin --> (Use3)
Admin -right-> (Use2)
Admin --> (Use1)

(Use1) ..> (Use2): <<include>>
(Use5) ..> (Use6): <<include>>
(Use5) ..> (Use3): <<include>>

@enduml